# Generated by Django 4.2.29 on 2026-03-20 07:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "unit_price_coins",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "subtotal_coins",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "shipping_fee_coins",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "brokerage_fee_coins",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="2% physical product brokerage fee paid by buyer",
                        max_digits=18,
                    ),
                ),
                (
                    "buyer_tx_fee_coins",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="2% buyer transaction fee",
                        max_digits=18,
                    ),
                ),
                (
                    "total_coins",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Total buyer pays (incl all fees)",
                        max_digits=18,
                    ),
                ),
                (
                    "commission_coins",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Platform commission deducted from vendor payout",
                        max_digits=18,
                    ),
                ),
                (
                    "vendor_payout_coins",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="What vendor actually receives",
                        max_digits=18,
                    ),
                ),
                (
                    "coupon_discount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("shipping_name", models.CharField(blank=True, max_length=200)),
                ("shipping_address_1", models.CharField(blank=True, max_length=300)),
                ("shipping_address_2", models.CharField(blank=True, max_length=300)),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_zip", models.CharField(blank=True, max_length=20)),
                ("shipping_country", models.CharField(blank=True, max_length=100)),
                ("shipping_phone", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("payment_received", "Payment Received"),
                            ("processing", "Processing"),
                            ("item_released", "Item Released by Vendor"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("verified", "Buyer Verified"),
                            ("disputed", "Disputed"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=25,
                    ),
                ),
                ("is_resale", models.BooleanField(default=False)),
                ("buyer_note", models.TextField(blank=True)),
                ("admin_note", models.TextField(blank=True)),
                ("dispute_reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coupon_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.coupon",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="listings.listing",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_received",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_coins",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Total buyer paid in coins (excl buyer fees)",
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("released", "Released to Vendor"),
                            ("refunded", "Refunded to Buyer"),
                            ("disputed", "Disputed"),
                            ("admin_hold", "Admin Hold"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("release_time", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("tx_hash", models.CharField(blank=True, max_length=300)),
                ("payment_address", models.CharField(blank=True, max_length=200)),
                ("admin_confirmed", models.BooleanField(default=False)),
                ("dispute_opened_at", models.DateTimeField(blank=True, null=True)),
                ("dispute_resolution_note", models.TextField(blank=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute_resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("physical", "Physical Shipping"),
                            ("service", "Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("delivery_link", models.URLField(blank=True, max_length=2000)),
                ("delivery_message", models.TextField(blank=True)),
                (
                    "vendor_released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When vendor clicked release item",
                        null=True,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Coin Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("payment", "Purchase Payment"),
                            ("escrow_lock", "Escrow Lock"),
                            ("escrow_release", "Escrow Release"),
                            ("escrow_refund", "Escrow Refund"),
                            ("commission", "Platform Commission"),
                            ("vendor_payout", "Vendor Payout"),
                            ("admin_credit", "Admin Credit"),
                            ("admin_debit", "Admin Debit"),
                            ("listing_fee", "Listing Fee"),
                            ("application_fee", "Application Fee"),
                            ("refund", "Refund"),
                            ("resale", "Resale Income"),
                            ("buyer_fee", "Buyer Transaction Fee"),
                            ("brokerage_fee", "Physical Brokerage Fee"),
                        ],
                        max_length=25,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("balance_after", models.DecimalField(decimal_places=8, max_digits=18)),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("tx_hash", models.CharField(blank=True, max_length=300)),
                ("admin_note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="orders_wall_user_id_f967b7_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="orders_wall_transac_9698fa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResaleRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resale_price", models.DecimalField(decimal_places=8, max_digits=18)),
                ("resale_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "original_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resale_origin",
                        to="orders.order",
                    ),
                ),
                (
                    "resale_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resale_transaction",
                        to="orders.order",
                    ),
                ),
                (
                    "reseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resale_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["reseller", "resale_date"],
                        name="orders_resa_reselle_bbd40a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status"], name="orders_orde_buyer_i_4389c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["vendor", "status"], name="orders_orde_vendor__d2c878_idx"
            ),
        ),
    ]
