# Generated by Django 4.2.29 on 2026-03-20 07:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("admin", "Admin"),
                            ("support", "Support"),
                            ("vendor", "Vendor"),
                            ("vendor_staff", "Vendor Staff"),
                            ("buyer", "Buyer"),
                            ("reseller", "Reseller"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("verified_vendor", models.BooleanField(default=False)),
                (
                    "coin_balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0E-8"), max_digits=18
                    ),
                ),
                (
                    "escrow_balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0E-8"), max_digits=18
                    ),
                ),
                (
                    "purchase_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed purchases"
                    ),
                ),
                (
                    "purchase_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("btc_address", models.CharField(blank=True, max_length=100)),
                ("usdt_trc20_address", models.CharField(blank=True, max_length=100)),
                ("ltc_address", models.CharField(blank=True, max_length=100)),
                ("ada_address", models.CharField(blank=True, max_length=100)),
                ("eth_address", models.CharField(blank=True, max_length=100)),
                ("xmr_address", models.CharField(blank=True, max_length=100)),
                ("withdrawal_address", models.CharField(blank=True, max_length=200)),
                (
                    "withdrawal_currency",
                    models.CharField(blank=True, default="USDT_TRC20", max_length=20),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("dark", "Dark"),
                            ("light", "Light"),
                            ("custom", "Custom"),
                        ],
                        default="dark",
                        max_length=10,
                    ),
                ),
                ("pgp_key", models.TextField(blank=True)),
                ("account_delete_time", models.DateTimeField(blank=True, null=True)),
                (
                    "last_active",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="PlatformWallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "coin_balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Wallet",
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_coins", models.DecimalField(decimal_places=8, max_digits=18)),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="USDT_TRC20", max_length=20)),
                ("address", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("param_name", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configurations",
            },
        ),
        migrations.CreateModel(
            name="DepositRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "coins_requested",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Number of TP Coins requested",
                        max_digits=18,
                    ),
                ),
                (
                    "usd_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="USD equivalent", max_digits=18
                    ),
                ),
                ("currency", models.CharField(default="USDT_TRC20", max_length=20)),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="Blockchain transaction hash / ID", max_length=300
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="deposits/screenshots/"
                    ),
                ),
                ("from_address", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("approved", "Approved — Coins Credited"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeletionQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("user_requested", "User Requested"),
                            ("inactive_low_balance", "Inactive + Low Balance"),
                            ("admin_action", "Admin Action"),
                            ("banned", "Account Banned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("record_id", models.CharField(max_length=50)),
                ("language_code", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                ("auto_translated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {
                    ("table_name", "field_name", "record_id", "language_code")
                },
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("ban", "Ban User"),
                            ("unban", "Unban User"),
                            ("escrow_override", "Escrow Override"),
                            ("config_change", "Config Change"),
                            ("balance_adjust", "Balance Adjustment"),
                            ("listing_remove", "Listing Removed"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("USDT_TRC20", "USDT (TRC20)"),
                            ("LTC", "Litecoin"),
                            ("ADA", "Cardano"),
                            ("ETH", "Ethereum"),
                            ("XMR", "Monero"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                (
                    "label",
                    models.CharField(
                        blank=True, default="Deposit Address", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "currency")},
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_active"], name="accounts_us_last_ac_e71e88_idx"
            ),
        ),
    ]
