# Generated by Django 4.2.30 on 2026-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='deposit_address',
            field=models.CharField(blank=True, help_text='Platform-assigned destination address used for this deposit', max_length=200),
        ),
    ]
