# Generated by Django 4.2.29 on 2026-03-20 07:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_price",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "current_bid",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "min_bid_increment",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.01"), max_digits=18
                    ),
                ),
                (
                    "buyout_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("original_end_time", models.DateTimeField()),
                ("extension_count", models.PositiveIntegerField(default=0)),
                ("total_extension_minutes", models.PositiveIntegerField(default=0)),
                ("anti_sniping", models.BooleanField(default=True)),
                ("auto_extend", models.BooleanField(default=True)),
                ("snipe_window_minutes", models.PositiveIntegerField(default=10)),
                ("extension_minutes", models.PositiveIntegerField(default=10)),
                ("max_extensions", models.PositiveIntegerField(default=5)),
                ("reserve_met", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("extended", "Extended (Anti-Snipe)"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction",
                        to="listings.listing",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_auctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction",
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bid_amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("is_winning", models.BooleanField(default=False)),
                ("is_auto_bid", models.BooleanField(default=False)),
                (
                    "max_auto_bid",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("triggered_extension", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auctions.auction",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-bid_amount", "-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["auction", "-bid_amount"],
                        name="auctions_bi_auction_d9f03d_idx",
                    ),
                    models.Index(
                        fields=["auction", "bidder"],
                        name="auctions_bi_auction_331710_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "end_time"], name="auctions_au_status_ced721_idx"
            ),
        ),
    ]
