# Generated by Django 4.2.29 on 2026-03-20 07:40

import apps.listings.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("physical", "Physical"),
                            ("service", "Service"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Price"), ("auction", "Auction")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("tags", models.CharField(blank=True, max_length=500)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="listings/thumbnails/"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("na", "N/A (Digital/Service)"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in USD — displayed as TP Coins to buyers",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="TP_COIN", max_length=20)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, help_text="0 = unlimited"),
                ),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                ("requires_shipping", models.BooleanField(default=False)),
                (
                    "shipping_fee_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("ships_from", models.CharField(blank=True, max_length=100)),
                ("ships_worldwide", models.BooleanField(default=True)),
                (
                    "estimated_delivery",
                    models.CharField(
                        blank=True, help_text="e.g. '3-7 business days'", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("active", "Active"),
                            ("sold_out", "Sold Out"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended by Admin"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("admin_verified", models.BooleanField(default=False)),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, help_text="Admin rejection/approval note"
                    ),
                ),
                ("fee_paid", models.BooleanField(default=False)),
                (
                    "auto_approved",
                    models.BooleanField(
                        default=False, help_text="Passed auto-approval rules"
                    ),
                ),
                ("resell_allowed", models.BooleanField(default=False)),
                ("max_resell_per_day", models.PositiveIntegerField(default=1)),
                ("external_links", models.JSONField(blank=True, default=list)),
                ("delivery_instructions", models.TextField(blank=True)),
                ("auto_delivery", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.listings.models.listing_file_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("is_public", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name e.g. 'hard-drive'",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "max_listings_per_vendor",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Max listings a single vendor can have in this category",
                    ),
                ),
                (
                    "min_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.01"),
                        help_text="Minimum listing price in USD for this category",
                        max_digits=10,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="listings.listingcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Listing Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.listingcategory",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="vendors.vendorprofile",
            ),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_order",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("usage_limit", models.PositiveIntegerField(default=1)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoApprovalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("keyword_blacklist", "Keyword Blacklist"),
                            ("min_price", "Minimum Price"),
                            ("max_price", "Maximum Price"),
                            ("category_block", "Category Blocked"),
                            ("type_block", "Type Blocked"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Keyword, price amount, category slug, or type"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("reject", "Reject listing"),
                            ("flag", "Flag for review"),
                        ],
                        default="reject",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Message shown to vendor on rejection",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "listing_type"], name="listings_li_status_7ee35b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["vendor", "status"], name="listings_li_vendor__c72994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-created_at"], name="listings_li_created_92fa22_idx"
            ),
        ),
    ]
