# Generated by Django 4.2.30 on 2026-09-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcategory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vendors.vendorprofile'),
        ),
        migrations.AddConstraint(
            model_name='listingcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', True)), fields=('slug',), name='unique_platform_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='listingcategory',
            constraint=models.UniqueConstraint(fields=('vendor', 'slug'), name='unique_vendor_category_slug'),
        ),
    ]
