# Generated by Django 4.2.30 on 2026-09-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingcategory_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcategory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
